// This Java program was generated by ChatGPT

public class J1_heapsort {

    public J1_heapsort() { }

    public static int test() {
        int[] a = new int[7];
        a[0] = 64;
        // J1_heapsort.heapSort(a);
        return a[0];
    }

}
